export const GET_LIST_TYPE_BOOK = 'GET_LIST_TYPE_BOOK',
GET_LIST_TYPE_BOOK_SUCCESS = 'GET_LIST_TYPE_BOOK_SUCCESS',
UPDATE_TYPE_BOOK = 'UPDATE_TYPE_BOOK',
DELETE_TYPE_BOOK = 'DELETE_TYPE_BOOK',
ADD_TYPE_BOOK = 'ADD_TYPE_BOOK' ;
