export const GET_LIST_TIME = 'GET_LIST_TIME',
GET_LIST_TIME_SUCCESS = 'GET_LIST_TIME_SUCCESS',
UPDATE_NOTIFICATION = 'UPDATE_NOTIFICATION',
DELETE_NOTIFICATION = 'DELETE_NOTIFICATION',
ADD_NOTIFICATION = 'ADD_NOTIFICATION' ;
