export const GET_LIST_PUBLISHING = 'GET_LIST_PUBLISHING',
GET_LIST_PUBLISHING_SUCCESS = 'GET_LIST_PUBLISHING_SUCCESS',
UPDATE_PUBLISHING = 'UPDATE_PUBLISHING',
DELETE_PUBLISHING = 'DELETE_PUBLISHING',
ADD_PUBLISHING = 'ADD_PUBLISHING' ;

