export const GET_LIST_RELEASE = 'GET_LIST_RELEASE',
GET_LIST_RELEASE_SUCCESS = 'GET_LIST_RELEASE_SUCCESS',
UPDATE_RELEASE = 'UPDATE_RELEASE',
DELETE_RELEASE = 'DELETE_RELEASE',
ADD_RELEASE = 'ADD_RELEASE' ;
