export const GET_LIST_KHACH_HANG = 'GET_LIST_KHACH_HANG',
GET_LIST_KHACH_HANG_SUCCESS = 'GET_LIST_KHACH_HANG_SUCCESS',
UPDATE_CUSTOMER = 'UPDATE_CUSTOMER',
DELETE_CUSTOMER = 'DELETE_CUSTOMER',
ADD_CUSTOMER = 'ADD_CUSTOMER' ;
