export const //SIGNUP
  SIGNUP = "SIGNUP",
  SIGNUP_SUCCESS = "SIGNUP_SUCCESS",
  //LOGIN
  LOGIN = "LOGIN",
  LOGIN_SUCCESS = "LOGIN_SUCCESS",
  //LOGOUT
  LOGOUT = "LOGOUT",
  //FORGOT PASSWORD
  FORGOT_PASSWORD = "FORGOT_PASSWORD",
  FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS",
  //RESET PASSWORD
  RESET_PASSWORD = "RESET_PASSWORD",
  RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS",
  // GET OC
  GET_OC = "GET_OC",
  GET_OC_SUCCESS = "GET_OC_SUCCESS";
