export const GET_LIST_REVENEU = 'GET_LIST_REVENEU',
    GET_LIST_REVENEU_SUCCESS = 'GET_LIST_REVENEU_SUCCESS',
    GET_LIST_TYPE_PRODUCT = 'GET_LIST_TYPE_PRODUCT ',
    GET_LIST_TYPE_PRODUCT_SUCCESS = 'GET_LIST_TYPE_PRODUCT_SUCCESS';
